<style>
    #loading_screen {
        background-color: #000000;
        border: medium none;
        display: none;
        height: 100%;
        left: 0;
        margin: 0;
        opacity: 0.7;
        padding: 0;
        position: fixed;
        top: 0;
        width: 100%;
        z-index: 100;
        text-align: center;
        filter: alpha(opacity = 70);
    }
    .loading { margin-top: 30%; }
    .loading img { width: 32px; height: 32px; }
</style>

<div id="loading_screen">
    <div class="loading"><img src="./img/loading.gif"></div>
</div>
<script type="text/javascript">
    //show loading div
    function show_loading() {
        jQuery("#loading_screen").css('display', 'block');
    }

    //hide loading div
    function hide_loading() {
        jQuery("#loading_screen").css('display', 'none');
    }
</script>