<div id="registration_modal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">
	
	<div class="modal-header">
		
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		
		<h3 id="myModalLabel">Registrierung</h3>
		
	</div>
	
	<div class="modal-body">
		
		<form class="form-inline">
			<div>
				<input type="text" id="register_email" name="register_email" class="input-small" placeholder="Email-Adresse" style="width: 180px;" />
				<div id="register_email_error">Bitte überprüfe die Email Adresse</div>
			</div>
			<div>
				<input type="password" id="register_password" name="register_password" class="input-small" placeholder="Passwort" style="width: 180px;" />
				<div id="register_password_error">Bitte überprüfe das Passwort (mindestens 6 Zeichen)</div>
			</div>
			<div>
				<input type="password" id="register_password_repeat" name="register_password_repeat" class="input-small" placeholder="Passwort wiederholen" style="width: 180px;" />
				<div id="register_password_repeat_error">Die Passwörter stimmen nicht überein</div>
			</div>
		</form>
		
	</div>
	
	<div class="modal-footer">
		
		<button class="btn" data-dismiss="modal"><i class="icon-remove">&nbsp;</i>Abbrechen</button>
		<button id="register_btn_login" class="btn btn-success"><i class="icon-pencil icon-white">&nbsp;</i>Registrieren</button>
		
	</div>
	
</div>