<div id="registration_modal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">
	
	<div class="modal-header">
		
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		
		<h3 id="myModalLabel">Registrierung</h3>
		
	</div>
	
	<div class="modal-body">
		
		<form class="form-inline">
			<div>
				<input type="text" id="register_email" name="register_email" class="input-small" placeholder="Email-Adresse" style="width: 180px;" />
			</div>
			<div>
				<input type="password" id="register_password" name="register_password" class="input-small" placeholder="Passwort" style="width: 180px;" />
			</div>
			<div>
				<button type="button" id="register_btn_login" name="register_btn_login" class="pull-right btn btn-mini">
					login
				</button>
			</div>
		</form>
		
	</div>
	
	<div class="modal-footer">
		
		<button class="btn" data-dismiss="modal"><i class="icon-remove"></i>Abbrechen</button>
		<button class="btn btn-success"><i class="icon-pencil icon-white"></i>Registrieren</button>
		
	</div>
	
</div>