<?php 
	
	$aa_inst_id = 0;
	
	if ( isset( $_GET[ 'aa_inst_id' ] ) ) { $aa_inst_id = $_GET[ 'aa_inst_id' ]; } else { echo json_encode( array( 'error' => 'missing instance id' ) ); exit( 0 ); }
	
	include_once '../../../init.php';
	
?>

<a id="auth_module_profile" href="#">profile</a>

<div id="auth_module_profile_content" class="hide" style="z-index: 10; position: absolute; background-color: lightgray; border: 1px solid black; width: 210px; text-align: center; padding: 10px;">
	
	<div>
		<b>Profil</b>
		<hr />
	</div>
	<form class="form-inline">
		<div>
			Eingelogged als:
			<span>
				<?php 
					
					$username = 'error';
					
print_r( $_SESSION[ 'userlogin_' . $aa_inst_id ] );
					
					if ( isset( $_SESSION[ 'userlogin_' . $aa_inst_id ] ) ) {
						if ( isset( $_SESSION[ 'userlogin_' . $aa_inst_id ][ 'userinstance' ][ 'email' ] ) &&
							 strlen( $_SESSION[ 'userlogin_' . $aa_inst_id ][ 'userinstance' ][ 'email' ] ) > 0 ) {
							$username = $_SESSION[ 'userlogin_' . $aa_inst_id ][ 'userinstance' ][ 'email' ];
						} else {
							if ( isset( $_SESSION[ 'userlogin_' . $aa_inst_id ][ 'userdata' ][ 'display_name' ] ) &&
							 	 strlen( $_SESSION[ 'userlogin_' . $aa_inst_id ][ 'userdata' ][ 'display_name' ] ) > 0 ) {
								$username = $_SESSION[ 'userlogin_' . $aa_inst_id ][ 'userdata' ][ 'display_name' ];
							}
						}
					}
					echo $username;
					
				?>
			</span>
		</div>
		<div>
			<button type="button" id="btn_logout" name="btn_logout" class="pull-right btn btn-mini btn-danger" style="margin-top: -20px;">
				Logout
			</button>
		</div>
	</form>
	
	<hr style="margin: 0px;" />
	
<!--
	<div>
		connected networks:
	</div>
-->
	
</div>

<script>
	
	// require the auth module because we are binding a module function call to the btn_login-onclick listener...
	// (without the auth module, a $(document).ready() function would have been enough...)
	require( [ 'jquery', 'gapi', 'auth' ], function ( $, gapi, auth ) {
		
		$(document).ready( function () {
			
			// fade in / fade out
			$( '#auth_module_profile' ).on( 'mouseover', function () {
				
				// the mouse is currently hovering over the <a>-login tag, so show the content...
				if ( $( '#auth_module_profile_content' ).is( ':visible' ) == false ) {
					
					// only fade the content in if it is not already showing
					$( '#auth_module_profile_content' ).fadeIn( 100, function () {
						
						$( '#email' ).focus();
						
					});
					
				}
				
			});
			
			$( '#auth_module_profile' ).on( 'mouseout', function () {
				
				if ( $( '#auth_module_profile_content' ).is( ':hover' ) == false ) {
					
					// the mouse pointer left the <a>-login tag, but did not move down to the content area, so fadeout...
					$( '#auth_module_profile_content' ).fadeOut( 100 );
					
				}
			});
			
			$( '#auth_module_profile_content' ).on( 'mouseout', function () {
				
				// check if the mouse pointer was moved upwards to the <a>-login tag, do not hide if so...
				if ( $( '#auth_module_profile_content' ).is( ':hover' ) == false && $( '#auth_module_profile' ).is( ':hover' ) == false ) {
					
					// if the mouse is not currently hovering over the content after hovering over the <a>-login tag hide the content...
					$( '#auth_module_profile_content' ).fadeOut( 100 );
					
				}
				
			});
			// end fade in / fade out
			
			
			// the logout-button function
			$( '#btn_logout' ).on( 'click', function () {
				
				$.ajax({
					url: 'modules/auth/logout_user.php?aa_inst_id=' + aa.inst.aa_inst_id,
					type: 'POST',
					dataType: 'JSON',
					data: {},
					success: function ( response ) {
						
						auth.init({
							placement: {
								// "template[0]" will be mapped to "toElement[0]" and so on...
								templates:  [ 'auth_navbar_item' ],
								toElements: [ '#menu_login' ]
							},
							debug: true
						});
						
					}
				});
				
			});
			
		});
		
	});
	
</script>