<?php 
	
?>

<a id="auth_module_profile" href="#">profile</a>

<div id="auth_module_profile_content" class="hide" style="z-index: 10; position: absolute; background-color: lightgray; border: 1px solid black; width: 210px; text-align: center; padding: 10px;">
	
	<div>
		<b>profile</b>
		<hr />
	</div>
	<form class="form-inline">
		<div>
			username
		</div>
		<div>
			<button type="button" id="btn_logout" name="btn_logout" class="pull-right btn btn-mini btn-danger">
				logout
			</button>
		</div>
	</form>
	
	<hr style="margin: 0px;" />
	
	<div>
		connected networks:
	</div>
	
</div>

<script>
	
	// require the auth module because we are binding a module function call to the btn_login-onclick listener...
	// (without the auth module, a $(document).ready() function would have been enough...)
	require( [ 'jquery', 'auth' ], function ( $, auth ) {
		
		$(document).ready( function () {
			
			// fade in / fade out
			$( '#auth_module_login' ).on( 'mouseover', function () {
				
				// the mouse is currently hovering over the <a>-login tag, so show the content...
				if ( $( '#auth_module_login_content' ).is( ':visible' ) == false ) {
					
					// only fade the content in if it is not already showing
					$( '#auth_module_login_content' ).fadeIn( 100, function () {
						
						$( '#email' ).focus();
						
					});
					
				}
				
			});
			
			$( '#auth_module_login' ).on( 'mouseout', function () {
				
				if ( $( '#auth_module_login_content' ).is( ':hover' ) == false ) {
					
					// the mouse pointer left the <a>-login tag, but did not move down to the content area, so fadeout...
					$( '#auth_module_login_content' ).fadeOut( 100 );
					
				}
			});
			
			$( '#auth_module_login_content' ).on( 'mouseout', function () {
				
				// check if the mouse pointer was moved upwards to the <a>-login tag, do not hide if so...
				if ( $( '#auth_module_login_content' ).is( ':hover' ) == false && $( '#auth_module_login' ).is( ':hover' ) == false ) {
					
					// if the mouse is not currently hovering over the content after hovering over the <a>-login tag hide the content...
					$( '#auth_module_login_content' ).fadeOut( 100 );
					
				}
				
			});
			// end fade in / fade out
			
			
			// the logout-button function
			$( '#btn_logout' ).on( 'click', function () {
				
				//TODO: log the user out
				auth.init({
					placement: {
						// "template[0]" will be mapped to "toElement[0]" and so on...
						templates:  [ 'auth_navbar_item' ],
						toElements: [ '#menu_login' ]
					},
					debug: true
				});
				
			});
			
		});
		
	});
	
</script>