<?php 
	
?>

<div id="auth_modal_password_recovery" class="modal hide fade in" role="dialog" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Passwort Wiederherstellung</h3>
	</div>
	<div class="modal-body">
		<p>Gib deine E-Mail Adresse ein mit der du dich registriert hast.</p>
		<p>Du erhältst dann eine E-Mail mit einem neuen Passwort und einem Link.</p>
		<p>Erst wenn du auf den Link in der E-Mail klickst wird dein Passwort zurückgesetzt.</p>
		<input id="email_recovery" name="email_recovery" type="email" placeholder="E-Mail für Wiederherstellung" />
		<div id="recovery_email_error" class="alert alert-error hide">Bitte überprüfe die E-Mail Adresse</div>
		<div id="recovery_general_error" class="alert alert-error hide"></div>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal">Abbrechen</button>
		<button id="get_recovery_email" class="btn btn-success">Passwort zurücksetzen</button>
	</div>
</div>

<script>
	
	// require the auth module because we are binding a module function call to the btn_login-onclick listener...
	// (without the auth module, a $(document).ready() function would have been enough...)
	require( [ 'jquery', 'auth' ], function ( $, auth ) {
		
		$(document).ready( function () {

			// init get recovery email button
			$( '#get_recovery_email' ).on( 'click', function () {
				
				var email = $( '#email_recovery' ).val();
				
				auth.forgot_password();
				
			});
			
		});
		
	});
	
</script>